### ISSUE TITLE
How can the gomod2nix.toml be generated inside the derivation ?

### ISSUE THREAD

**Issue by 573** [tweag/gomod2nix#18]
**Is your feature request related to a problem? Please describe.**
I'm trying to convert a go project to nix using this default.nix:
```nix
let
  pkgs = import <nixpkgs> {
    overlays = [
      (self: super: {
        buildGoApplication = pkgs.callPackage ("${builtins.fetchTarball {
          url =  https://github.com/tweag/gomod2nix/archive/67f22dd738d092c6ba88e420350ada0ed4992ae8.tar.gz;
          sha256 = "0a9rhw6djgcrky5nzly3srsl8095q42f2nyzxyisp9fh9fg70nih";
        }}/builder") {};
        gomod2nix = pkgs.callPackage ("${builtins.fetchTarball {
          url =  https://github.com/tweag/gomod2nix/archive/67f22dd738d092c6ba88e420350ada0ed4992ae8.tar.gz;
          sha256 = "0a9rhw6djgcrky5nzly3srsl8095q42f2nyzxyisp9fh9fg70nih";
        }}/default.nix") {};
      })
    ];
  };
  # for available attrs check
  # nix-repl> :l default.nix
  # nix-repl> out.drvAttrs
in pkgs.buildGoApplication rec {
  pname = "zk";
  version = "main";
  #src = ./.;
  src = builtins.fetchGit{
    url = "https://github.com/mickael-menu/zk";
    ref = "main";
    rev = "8c7ec93ca53e8a67e69e49bc24fc6a4567683193";
  };
  patches = [ ./0001-Add-gomod2nix.toml.patch ];
  postPatch = ''
    readlink -f gomod2nix.toml
    head gomod2nix.toml
    '';
  pwd = src;
  modules = "${pwd}/gomod2nix.toml";
  doCheck = false;
  CGO_ENABLED = "1";
}
```

~What is problematic is that t~The gomod2nix.toml exists only after the patch phase and thus I can't specify a useful modules attribute right now. Reason of not just using a local clone is I want to rely just on the sources fetched via git so I can pin the go project's version better.

**Describe the solution you'd like**
~The `module` attribute should be possible to set in a lazy manner~It should be possible to run gomod2nix in a `runCommand`, such that it is possible to convert go projects on-the-fly that have no gomod2nix.toml file yet.

~**Describe alternatives you've considered**
#6 states that before module resolution it fetches the repo, so this could be a solution.~

**Comment by 573** [comment]
With a rewrite of default.nix
```nix
{pkgs ? import <nixpkgs> {}}:
let
  sources = import ./../../../nix/sources.nix;

  in with { overlay = _: pkgs:
    { niv = (import sources.niv {}).niv;
    };
  };
let
   nixpkgs = sources."nixpkgs";

   pkgs = import nixpkgs {
     overlays = [
       overlay
       (import "${builtins.fetchTarball {
          url = "https://github.com/${sources.gomod2nix.owner}/${sources.gomod2nix.repo}/archive/${sources.gomod2nix.rev}.tar.gz";
          sha256 = sources.gomod2nix.sha256;
        }}/overlay.nix")
    ]; config = {};
  };
  # for available attrs check
  # nix-repl> :l default.nix
  # nix-repl> out.drvAttrs
in pkgs.buildGoApplication rec {
  pname = "zk";
  version = "main";
  src = pkgs.runCommand "fetchandpatch" {
    input = builtins.fetchGit{
      url = "https://github.com/mickael-menu/zk";
      ref = "main";
      rev = "8c7ec93ca53e8a67e69e49bc24fc6a4567683193";
    };
  } ''
    ${pkgs.gomod2nix}/bin/gomod2nix --help
    echo \$input: $(readlink -f $input)
    echo gomod2nix.toml: $(readlink -f gomod2nix.toml)
    ${pkgs.gomod2nix}/bin/gomod2nix -dir $input
    '';
  pwd = src;
  modules = "$pwd/gomod2nix.toml";
  doCheck = false;
  CGO_ENABLED = "1";
}
```

I now get

>Usage of /nix/store/276bqjspzqjncrc9fipnm9hmj3vjp5yq-gomod2nix-0.1/bin/gomod2nix:
  -dir string
    	Go project directory (default "./")
  -format string
    	output format (gomod2nix, buildgopackage) (default "gomod2nix")
  -jobs int
    	Number of max parallel jobs (default 10)
  -keep-going
    	Whether to panic or not if a rev cannot be resolved (default "false")
  -outdir string
    	output directory (if different from project directory)
$input: /nix/store/cqvlgw6i65lc34pmrzjini98wq29djjr-source
gomod2nix.toml: /tmp/nix-build-fetchandpatch.drv-0/gomod2nix.toml
[36mINFO[0m[0000] Using output format 'gomod2nix'              
[36mINFO[0m[0000] Parsing go.mod                                [36mmodPath[0m=/nix/store/cqvlgw6i65lc34pmrzjini98wq29djjr-source/go.mod
open /nix/store/cqvlgw6i65lc34pmrzjini98wq29djjr-source/gomod2nix.toml: no such file or directory
[36mINFO[0m[0000] Parsing go.sum                                [36msumPath[0m=/nix/store/cqvlgw6i65lc34pmrzjini98wq29djjr-source/go.sum
[36mINFO[0m[0000] Starting worker processes                     [36mnumWorkers[0m=10
[36mINFO[0m[0000] Queuing jobs                                  [36mnumJobs[0m=347
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=10
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=gopkg.in/yaml.v3 [36mworkerId[0m=10
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=4
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=0
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/beevik/etree [36mworkerId[0m=0
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/beevik/etree [36mrev[0m=v1.1.0
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=2
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/google/pprof [36mworkerId[0m=2
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=8
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/googleapis/gnostic [36mworkerId[0m=8
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=1
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/googleapis/gnostic [36mrev[0m=v0.4.1
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/munnerz/goautoneg [36mworkerId[0m=1
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/google/pprof [36mrev[0m=fc25d7d30c6d
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=sigs.k8s.io/structured-merge-diff/v4 [36mworkerId[0m=4
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=9
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=5
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/julienschmidt/httprouter [36mworkerId[0m=5
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/julienschmidt/httprouter [36mrev[0m=v1.2.0
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/munnerz/goautoneg [36mrev[0m=a7dc8b61c822
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=7
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/kr/text [36mworkerId[0m=7
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/kr/text [36mrev[0m=v0.2.0
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=6
[36mINFO[0m[0000] Starting worker process                       [36mworkerId[0m=3
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/andybalholm/cascadia [36mworkerId[0m=3
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=cloud.google.com/go/bigquery [36mworkerId[0m=6
[36mINFO[0m[0000] Worker received job                           [36mgoPackagePath[0m=github.com/hpcloud/tail [36mworkerId[0m=9
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/hpcloud/tail [36mrev[0m=v1.0.0
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/andybalholm/cascadia [36mrev[0m=v1.1.0
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=sigs.k8s.io/structured-merge-diff/v4 [36mrev[0m=v4.1.0
[36mINFO[0m[0000] Cache miss, fetching                          [36mgoPackagePath[0m=gopkg.in/yaml.v3 [36mrev[0m=496545a6307b
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/google/pprof [36mrev[0m=/fc25d7d30c6d
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/munnerz/goautoneg [36mrev[0m=/a7dc8b61c822
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/hpcloud/tail [36mrev[0m=/v1.0.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/beevik/etree [36mrev[0m=/v1.1.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/googleapis/gnostic [36mrev[0m=/v0.4.1
[36mINFO[0m[0001] Cache miss, fetching                          [36mgoPackagePath[0m=cloud.google.com/go/bigquery [36mrev[0m=v1.4.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/kr/text [36mrev[0m=/v0.2.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/andybalholm/cascadia [36mrev[0m=/v1.1.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=github.com/julienschmidt/httprouter [36mrev[0m=/v1.2.0
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=gopkg.in/yaml.v3 [36mrev[0m=/496545a6307b
[36mINFO[0m[0001] Fetching failed, retrying with different rev format  [36mgoPackagePath[0m=sigs.k8s.io/structured-merge-diff/v4 [36mrev[0m=/v4.1.0
[31mERRO[0m[0002] Fetching failed                               [31mgoPackagePath[0m=github.com/google/pprof
[36mINFO[0m[0002] Worker received job                           [36mgoPackagePath[0m=github.com/armon/go-metrics [36mworkerId[0m=2
[36mINFO[0m[0002] Cache miss, fetching                          [36mgoPackagePath[0m=github.com/armon/go-metrics [36mrev[0m=f0300d1749da
[36mINFO[0m[0002] Received finished job                         [36mcurrent[0m=1 [36mtotal[0m=347
panic: exit status 1
>
>goroutine 1 [running]:
main.main()
	/tmp/nix-build-gomod2nix-0.1.drv-0/source/main.go:50 +0x9f3

**Comment by 573** [comment]
I would like to change the problem statement to "How can the gomod2nix.toml be generated inside the derivation ?"

Reason: When the gomod2nix.toml does not (yet) exist in a derivations resources I also cannot generate it while using `modules = ./gomod2nix.toml;` in that same derivation.

**Comment by adisbladis** [comment]
This will never be possible as it's not a pure transformation, we need to hit the network.
