### ISSUE TITLE
[Question]: Is there a way to tell gomod2nix to skip a subPackage?

### ISSUE THREAD

**Issue by JonathanLorimer** [tweag/gomod2nix#19]
I am trying to package https://github.com/cosmos/cosmos-sdk and one of the subdirectories is not a package but a module. When I try to build `cosmos-sdk` via `buildGoApplication` it fails on `cosmovisor` (the module in a subdirectory), is there any way I can tell buildGoApplication to skip this?

**Comment by doronbehar** [comment]
I think you can use the `subPackages` undocumented argument just like you'd use it in Nixpkgs.
