### ISSUE TITLE
gomod2nix will hash `.DS_Store` file into output hash

### ISSUE THREAD

**Issue by yihuang** [tweag/gomod2nix#49]
With recent refactoring `gomod2nix` runs much faster now, because it use the host go and the go pkg cache directory, but one problem is, macos create `.DS_Store` files into directory automatically, which makes the output hash computed incorrect.

**Comment by adisbladis** [comment]
We could simply filter it out when creating the NAR, but that's not strictly correct..
It's probably what we'll end up doing though.

**Comment by adisbladis** [comment]
I've implemented the requisite functionality in https://github.com/nix-community/go-nix/pull/46.
Waiting for it to be merged.
