### ISSUE TITLE
Design assumption / dependency graph

### ISSUE THREAD

**Issue by dgnorton** [tweag/gomod2nix#67]
The blog post introducing [gomod2nix](https://www.tweag.io/blog/2021-03-04-gomod2nix/) states:

> After squinting at these files for a while we can already see some radical differences in semantics, most notably that go.sum is structured as a flat list rather than a graph. Of course, all dependencies to the build are listed in go.sum, but we don’t know what depends on what. What this means for us in Nix is that we have no good unit of incrementality — everything has to be built together — while Poetry can build dependencies separately.

Would the output of `go mod graph` suffice? (https://go.dev/ref/mod#go-mod-graph) E.g.,

```
git clone https://github.com/benbjohnson/tmpl
cd tmpl
go mod graph
```
Outputs:
```
➜  tmpl git:(master) go mod graph
github.com/benbjohnson/tmpl github.com/Masterminds/goutils@v1.1.1
github.com/benbjohnson/tmpl github.com/Masterminds/semver@v1.5.0
github.com/benbjohnson/tmpl github.com/Masterminds/sprig@v2.22.0+incompatible
github.com/benbjohnson/tmpl github.com/dustin/go-humanize@v1.0.0
github.com/benbjohnson/tmpl github.com/google/uuid@v1.2.0
github.com/benbjohnson/tmpl github.com/huandu/xstrings@v1.3.2
github.com/benbjohnson/tmpl github.com/imdario/mergo@v0.3.12
github.com/benbjohnson/tmpl github.com/mitchellh/copystructure@v1.1.1
github.com/benbjohnson/tmpl github.com/stretchr/testify@v1.7.0
github.com/benbjohnson/tmpl golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2
github.com/imdario/mergo@v0.3.12 gopkg.in/yaml.v2@v2.3.0
github.com/mitchellh/copystructure@v1.1.1 github.com/mitchellh/reflectwalk@v1.0.1
github.com/stretchr/testify@v1.7.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.7.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.7.0 github.com/stretchr/objx@v0.1.0
github.com/stretchr/testify@v1.7.0 gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c
golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2 golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110
golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2 golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68
golang.org/x/crypto@v0.0.0-20210322153248-0c34fe9e7dc2 golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
gopkg.in/yaml.v2@v2.3.0 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110 golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68
golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110 golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110 golang.org/x/text@v0.3.3
golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1 golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68
golang.org/x/text@v0.3.3 golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e
```

**Comment by adisbladis** [comment]
> Would the output of go mod graph suffice? (https://go.dev/ref/mod#go-mod-graph) E.g.,

It would in theory, at the time that post was written `go mod graph` didn't exist though.

In practice it doesn't quite work out though, I experimented with various approaches to use the data generated by `go mod graph` but the way that `go` constructs it's caches are not really conducive to incremental building using Nix derivations.

In the end the build times were _longer_ for almost every package I tried because of having to deal with populating, copying and merging caches.

Thank you for the issue. I would really have loved for incremental builds to have worked out, but sadly it didn't.
